spring:
  datasource:
    url: jdbc:sqlite:inventory.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  api-key: INVENTORY_SERVICE_KEY